apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ruxandras-portal
  description: An example of a Backstage application.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ruxandra-sketch/ruxandras-portal
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
